config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

hobbyst/account/urls.py
from django.urls import path
from account.views import (login_view,logout_view,signup,
                        profile,followers,following,
                        follow,RegisterUsers)

app_name = "account"
urlpatterns = [
    path("login/", login_view.as_view(), name="login"),
    path("logout/", logout_view.as_view(), name="logout"),
    path("signup/", signup.as_view(), name="signup"),
    path("<int:user_id>/profile/", profile.as_view(), name="profile"),
    path("<int:user_id>/followers/", followers.as_view(), name="followers"),
    path("<int:user_id>/following/", following.as_view(), name="following"),
    path("<int:user_id>/follow/", follow.as_view(), name="follow"),
    path('registerusers/', RegisterUsers.as_view()),
]

AUTH_USER_MODEL = 'accounts.User'

hobbyst/board/urls.py
from django.urls import path
from board.views import (
    home,
    comment_add,
    comment_delete,
    post_add,
    tags,
    post_detail,
    post_like,
    feed_page,
)

app_name = "board"
urlpatterns = [
    path("", home, name="home"),
    path("comment_add/", comment_add, name="comment_add"),
    path("comments/<int:comment_id>/delete/", comment_delete, name="comment_delete"),
    path("post_add/", post_add, name="post_add"),
    path("tags/<str:tag_name>/", tags, name="tags"),
    path("<int:post_id>/", post_detail, name="post_detail"),
    path("<int:post_id>/like/", post_like, name="post_like"),
    path("feed/", feed_page, name="feed_page"),
]

pyburger/urls.py
from django.contrib import admin
from django.urls import path
from config.views import main,burger_list,burger_search

urlpatterns = [
    path('admin/', admin.site.urls),
    path ("", main),
    path("burgers/", burger_list),
    path("search/", burger_search),
]

pydrf/config/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path("admin/", admin.site.urls),
    path("example/", include("example.urls"))
]

pylog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from config.views import index
from blog.views import post_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index),
    path("posts/", post_list),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

hobbyst/board/models.py
from django.db import models

# from account.models import User
# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(
        "account.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    content = models.TextField("내용", blank=True)
    created = models.DateTimeField("생성일시", auto_now_add=True)
    tags = models.ManyToManyField(
        "board.HashTag", verbose_name="해시태그 목록", blank=True
    )

    def __str__(self):
        return f"{self.user.username}의 Post(id: {self.id})"


class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE,
    )
    photo = models.ImageField("사진", upload_to="post")


class Comment(models.Model):
    user = models.ForeignKey(
        "account.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)


class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name

hobbyst/board/forms.py
from django import forms

from board.models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "post",
            "content",
        ]
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "placeholder": "댓글 달기...",
                }
            )
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "content",
        ]

hobbyst/hobbyst/board/forms.py
from django import forms

from board.models import Comment, Post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "post",
            "content",
        ]
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "placeholder": "댓글 달기...",
                }
            )
        }

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "content",
        ]

hobbyst/account/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from account.forms import LoginForm, SignupForm
from account.models import User
from rest_framework import status, generics, mixins#, viewsets, permissions
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.decorators import api_view
from .serializers import RegisterSerializer

# Create your views here.
def login_view(request):
    if request.user.is_authenticated:
        return redirect("board:home")

    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                return redirect("board:home")
            else:
                # print('로그인에 실패했습니다')
                form.add_error(None, "입력한 자격증명에 해당하는 사용자가 없습니다")

        context = {"form": form}
        return render(request, "account/login.html", context)
    else:
        form = LoginForm()
        context = {"form": form}
        return render(request, "account/login.html", context)


def logout_view(request):
    logout(request)
    return redirect("account:login")


def signup(request):
    if request.method == "POST":
        form = SignupForm(data=request.POST, files=request.FILES)

        if form.is_valid():
            user = form.save()
            # login(request, user) ## 회원가입 후 로그인 한 뒤 들어가도록
            return redirect("account:login")
        else:
            context = {"form": form}
            return render(request, "account/signup.html", context)
    else:
        form = SignupForm()

    context = {"form": form}
    return render(request, "account/signup.html", context)


def profile(request, user_id):
    user = get_object_or_404(User, id=user_id)
    context = {
        "user": user,
    }
    return render(request, "account/profile.html", context)


def followers(request, user_id):
    user = get_object_or_404(User, id=user_id)
    relationships = user.follower_relationships.all()
    context = {
        "user": user,
        "relationships": relationships,
    }
    return render(request, "account/followers.html", context)


def following(request, user_id):
    user = get_object_or_404(User, id=user_id)
    relationships = user.following_relationships.all()
    context = {
        "user": user,
        "relationships": relationships,
    }
    return render(request, "account/following.html", context)


def follow(request, user_id):

    user = request.user

    target_user = get_object_or_404(User, id=user_id)

    if target_user in user.following.all():
        user.following.remove(target_user)

    else:
        user.following.add(target_user)

    url_next = request.GET.get("next") or reverse("account:profile", args=[user.id])
    return HttpResponseRedirect(url_next)

class RegisterUsers(APIView):
   def get(self, request):
        users = User.objects.all()
        serializer = RegisterSerializer(users, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)
        

hobbyst/board/views.py
from django.http import (
    HttpResponseBadRequest,
    HttpResponseRedirect,
    HttpResponseForbidden,
)

from django.shortcuts import render, redirect
from django.urls import reverse

from board.models import Post, Comment, PostImage, HashTag
from board.forms import CommentForm, PostForm

# Create your views here.


def home(request):
    user = request.user
    if not request.user.is_authenticated:
        return redirect("account:login")
    posts = Post.objects.all().order_by("-created")
    tags = HashTag.objects.all()
    comment_form = CommentForm()
    context = {
        "posts": posts,
        "tags": tags,
        "comment_form": comment_form,
    }

    return render(request, "board/home.html", context)


# 댓글 작성을 처리할 View
def comment_add(request):
    if request.method == "GET":
        # 이 View에 GET요청이 전달되면, 잘못된 요청임을 브라우저에 알려준다.
        return HttpResponseBadRequest()

    # request.POST로 전달된 데이터를 사용해 CommentForm인스턴스를 생성
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # commit=False옵션으로 메모리상에 Comment객체 생성
        comment = form.save(commit=False)

        # Comment생성에 필요한 사용자정보를 request에서 가져와 할당
        comment.user = request.user

        # DB에 Comment객체 저장
        comment.save()

        # URL로 "next"값을 전달받았다면 댓글 작성 완료 후 전달받은 값으로 이동한다
        if request.GET.get("next"):
            url_next = request.GET.get("next")

        # "next"값을 전달받지 않았다면 피드페이지의 글 위치로 이동한다
        else:
            url_next = reverse("board:home") + f"#post-{comment.post.id}"

        return HttpResponseRedirect(url_next)


def comment_delete(request, comment_id):
    if request.method == "POST":
        comment = Comment.objects.get(id=comment_id)
        if comment.user == request.user:
            comment.delete()
            url = reverse("board:home") + f"#post-{comment.post.id}"
            return HttpResponseRedirect(url)
        else:
            return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다")
    else:
        # 이 View에 오는 GET요청은 잘못되었다고 브라우저에 돌려준다
        return HttpResponseBadRequest()


def post_add(request):
    if request.method == "POST":
        # request.POST로 온 데이터 ("content")는 PostForm으로 처리
        form = PostForm(request.POST)

        if form.is_valid():
            # Post의 "user"값은 request에서 가져와 자동할당한다
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            # Post를 생성 한 후
            # request.FILES.getlist("images")로 전송된 이미지들을 순회하며 PostImage객체를 생성한다
            for image_file in request.FILES.getlist("images"):
                # request.FILES또는 request.FILES.getlist()로 가져온 파일은
                # Model의 ImageField부분에 곧바로 할당한다
                PostImage.objects.create(
                    post=post,
                    photo=image_file,
                )

            # "tags"에 전달 된 문자열을 분리해 HashTag생성
            tag_string = request.POST.get("tags")
            if tag_string:
                tag_name_list = [tag_name.strip() for tag_name in tag_string.split(",")]
                for tag_name in tag_name_list:
                    tag, _ = HashTag.objects.get_or_create(
                        name=tag_name,
                    )
                    # get_or_create로 생성하거나 가져온 HashTag객체를 Post의 tags에 추가한다
                    post.tags.add(tag)

            # 모든 PostImage와 Post의 생성이 완료되면
            # 피드페이지로 이동하여 생성된 Post의 위치로 스크롤되도록 한다
            url = reverse("board:home") + f"#post-{post.id}"
            return HttpResponseRedirect(url)

    # GET요청일 때는 빈 form을 보여주도록한다
    else:
        form = PostForm()

    context = {"form": form}
    return render(request, "board/post_add.html", context)


def tags(request, tag_name):
    try:
        tag = HashTag.objects.get(name=tag_name)
    except HashTag.DoesNotExist:
        # tag_name에 해당하는 HashTag를 찾지 못한 경우 빈 QuerySet을 돌려준다
        posts = Post.objects.none()
    else:
        posts = Post.objects.filter(tags=tag)

    # context로 Template에 필터링 된 Post QuerySet을 넘겨주며,
    # 어떤 tag_name으로 검색했는지도 넘겨준다
    context = {
        "tag_name": tag_name,
        "posts": posts,
    }
    return render(request, "board/tags.html", context)


def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comment_form = CommentForm()
    context = {
        "post": post,
        "comment_form": comment_form,
    }
    return render(request, "board/post_detail.html", context)


# URL에서 좋아요 처리할 Post의 id를 전달받는다.
def post_like(request, post_id):
    post = Post.objects.get(id=post_id)
    user = request.user

    # 사용자가 "좋아요를 누른 Post목록"에 "좋아요 버튼을 누른 Post"가 존재한다면
    if user.like_posts.filter(id=post.id).exists():
        # 좋아요 목록에서 삭제한다
        user.like_posts.remove(post)

    # 존재하지 않는다면 좋아요 목록에 추가한다.
    else:
        user.like_posts.add(post)

    # next로 값이 전달되었다면 해당 위치로, 전달되지 않았다면 피드페이지에서 해당 Post위치로 이동한다
    url_next = request.GET.get("next") or reverse("board:home") + f"#post-{post.id}"

    return HttpResponseRedirect(url_next)


def feed_page(request):
    user = request.user
    if not request.user.is_authenticated:
        return redirect("account:login")
    posts = Post.objects.all()
    comment_form = CommentForm()
    context = {
        "posts": posts,
        "comment_form": comment_form,
    }
    return render(request, "board/feed_page.html", context)

hobbyst/config/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html")

hobbyst/hobbyst/account/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from account.forms import LoginForm, SignupForm
from account.models import User

# Create your views here.
def login_view(request):
    if request.user.is_authenticated:
        return redirect("board:home")
    
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            if user :
                login(request, user)
                return redirect("board:home")
            else:
                # print('로그인에 실패했습니다')
                form.add_error(None, "입력한 자격증명에 해당하는 사용자가 없습니다")

        context = {'form':form}
        return render(request, 'account/login.html', context)
    else:
        form = LoginForm()
        context = {'form':form}
        return render(request, 'account/login.html', context)
    

def logout_view(request):
    logout(request)
    return redirect("account:login")

def signup(request):
    if request.method == 'POST':
        form = SignupForm(data=request.POST, files=request.FILES)

        if form.is_valid():
            user = form.save()
            # login(request, user) ## 회원가입 후 로그인 한 뒤 들어가도록
            return redirect("account:login")
        else:
            context = {'form':form}
            return render(request, 'account/signup.html', context)
    else:
        form = SignupForm()

    context = {'form':form}
    return render(request, 'account/signup.html', context)

def profile(request, user_id):
    user = get_object_or_404(User, id=user_id)
    context = {
        "user":user,
    }
    return render(request, "account/profile.html", context)

def followers(request, user_id):
    user = get_object_or_404(User, id=user_id)
    relationships = user.follower_relationships.all()
    context = {
        'user':user,
        'relationships':relationships,
    }
    return render(request, 'account/followers.html', context)

def following(request, user_id):
    user = get_object_or_404(User, id=user_id)
    relationships = user.following_relationships.all()
    context = {
        'user':user,
        'relationships':relationships,
    }
    return render(request, 'account/following.html', context)

def follow(request, user_id):

    user = request.user

    target_user = get_object_or_404(User, id=user_id)

    if target_user in user.following.all():
        user.following.remove(target_user)
    
    else:
        user.following.add(target_user)

    
    url_next = request.GET.get('next') or reverse('account:profile', args=[user.id])
    return HttpResponseRedirect(url_next)

hobbyst/hobbyst/config/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

hobbyst/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>HOBBYST</title>
    {% block head %}{% endblock %}
</head>
<body>
    {% block base_content %}{% endblock %}
</body>
</html>

hobbyst/templates/base.html
{% extends '_base.html' %}

{% block base_content %}
    {% block content %}{% endblock %}
{% endblock %}

hobbyst/templates/base_nav.html
{% extends '_base.html' %}

{% block base_content %}
    {% include 'nav.html' %}
    {% block content %}{% endblock %}
{% endblock %}

hobbyst/templates/base_profile.html
{% extends 'base_nav.html' %}

{% block content %}
<div id="profile">
    <div class="info">
        {% if user.profile_image %}
            <img src="{{ user.profile_image.url }}">
        {% endif %}

        <div class="info-texts">
            <h1>{{ user.username }}</h1>
            <div class="counts">
                <dl>
                    <dt>Posts</dt>
                    <dd>
                        <a href="{% url 'account:profile' user_id=user.id %}">{{ user.post_set.count }}</a>
                    </dd>
                    <dt>Followers</dt>
                    <dd>
                        <a href="{% url 'account:followers' user_id=user.id %}">
                            {{ user.followers.count }}
                        </a>
                    </dd>
                    <dt>Following</dt>
                    <dd>
                        <a href="{% url 'account:following' user_id=user.id %}">
                            {{ user.following.count }}
                        </a>
                    </dd>
                </dl>
            </div>
            <p>{{ user.short_description }}</p>
            <p>선호하는 취미 카테고리 : {{ user.preference }}</p>
        </div>
    </div>
    {% block bottom_data %}{% endblock %}
</div>
{% endblock %}

hobbyst/templates/base_slider.html
{% extends '_base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'splide/splide.css' %}">
    <script src="{% static 'splide/splide.js' %}"></script>
{% endblock %}

{% block base_content %}
    {% include 'nav.html' %}
    {% block content %}{% endblock %}
    <script>
        const elms = document.getElementsByClassName('splide');
        for (let i = 0; i < elms.length; i++) {
            new Splide(elms[i]).mount();
        }
    </script>
{% endblock %}

hobbyst/templates/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index=start page</title>
    <style>
        body {
            font-family: 'Noto Sans KR', sans-serif;
            background-color: #333;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        /*.container {
            background-color: white;
            padding: 40px 60px;
            border-radius: 12px;
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
            text-align: center;
            max-width: 400px;
            width: 100%;
        }*/
        h1 {
            font-size: 96px;
            color: white;
            margin-bottom: 20px;
            font-weight: bold;
        }
        p {
            font-size: 32px;
            color: white;
            margin-bottom: 30px;
        }
       a {
            display: inline-block;
            justify-content: center;
            align-items: center;
            padding: 12px 25px;
            background-color: #0095f6;
            color: white;
            text-decoration: none;
            border-radius: 6px;
            font-size: 32px;
            transition: background-color 0.3s ease-in-out, transform 0.2s ease-in-out;
        } 
        a:hover {
            background-color: rgba(255, 255, 255, 0.815);
            transform: translateY(-3px);
        }
        .subtext {
            margin-top: 15px;
            font-size: 14px;
            color: white;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>HOBBYST</h1>
        <p>최고의 최상의 최적의</p>
        <p>취미 찾기 커뮤니티</p>
        <a href="/account/login">시작하기</a>
    </div>
</body>
</html>

hobbyst/templates/nav.html
{% load static %}
<style>
    .logo {
        height: 30px;  /* Adjust as needed */
        margin-right: 10px;
        margin-top: 10px;
        transform: scale(1.5);
    }
</style>
<nav>
    <img src="{% static 'logo/logo.png' %}" alt="HOBBYST Logo" class="logo">
    <h1><a href="{% url 'board:home' %}">HOBBYST</a></h1>
    <a href="{% url 'board:feed_page' %}">Feeds</a>
    <a href="{% url 'board:post_add' %}">Addpost</a>
    <a href="{% url 'account:profile' user_id=request.user.id %}">Mypage</a>
    <a href="{% url 'account:logout' %}">Logout</a>
</nav>